
server:
  port: 9999


spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oikomi/FishChatServerJava/
        searchPaths: configrepo
      label: master

